### ISSUE TITLE
De-serialization of Arc broken 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/PowerSystems.jl#966]
as a consequence of adding a type union to the Arcs, the de-serialization broke.

**Comment by rodrigomha** [comment]
I think is better to go with the older approach. Use Arc for AC Branches and create a DCArc for models of DC Branches. At least I prefer that one.

**Comment by jd-lara** [comment]
It makes no sense to have AC and DC arcs. Those are just Arcs. There is no additional topological gains by making 2 types.

**Comment by rodrigomha** [comment]
Yeah, this looks like an issue related to handling Unions in deserialization. Here is a MWE for this issue:
```
nodes_mwe() = [
    ACBus(1, "nodeA", "REF", 0, 1.0, (min = 0.9, max = 1.05), 230, nothing, nothing),
    ACBus(2, "nodeB", "PQ", 0, 1.0, (min = 0.9, max = 1.05), 230, nothing, nothing),
]

branches_mwe(nodes) = [
    Line(
        "nodeA-nodeB",
        true,
        0.0,
        0.0,
        Arc(from = nodes[1], to = nodes[2]),
        0.00281,
        0.0281,
        (from = 0.00356, to = 0.00356),
        2.0,
        (min = -0.7, max = 0.7),
    ),
]

nodes_val = nodes_mwe()
sys = System(100.0, nodes_val, branches_mwe(nodes_val))
to_json(sys, "sys_json.json", force=true)
sys = System("sys_json.json")
```

The error is this one:
```
ERROR: MethodError: no method matching fieldnames(::Type{Union{ACBus, DCBus}})
Closest candidates are:
  fieldnames(::Core.TypeofBottom) at reflection.jl:188
  fieldnames(::Type{<:Tuple}) at reflection.jl:190
  fieldnames(::DataType) at reflection.jl:185
  ...
```

I'll discuss with @daniel-thom to figure this out.

**Comment by rodrigomha** [comment]
Fixed in #969

**Comment by jd-lara** [comment]
This issue still shows up when running PSB 

MWE on a clean environment 
```sys_rts_da = build_system(PSISystems, "sys10_pjm_ac_dc");
sys_rts_da = build_system(PSISystems, "sys10_pjm_ac_dc");
```

**Comment by jd-lara** [comment]
closed again via ec7bea40f9192c22758f4988d1f8fda7449245ca
